[package]
name = "engine"
version = "0.1.0"
authors = ["Aurora Morgan <aurora@aventine.se>"]

[[bin]]
name = "eve-toolbox"

[dependencies]
xml-rs = "*"
eventual = "*"
rustc-serialize = "*"

[dependencies.hyper]
version = "*"
default-features = false